### ISSUE TITLE
"An error occurred, pls report this to the developer."

### ISSUE THREAD

**Issue by vbh689** [AaronFeng753/Waifu2x-Extension#9]
I experienced this error while scaling my images, it was OK since 17/20 pictures.
Then the problem suddenly occurred.

```
---------------------------------------------------
                   !!! Error !!!
---------------------------------------------------
Traceback (most recent call last):
  File "Waifu2x-Extension.py", line 6820, in <module>
    init()
  File "Waifu2x-Extension.py", line 6796, in init
    MainMenu()
  File "Waifu2x-Extension.py", line 258, in MainMenu
    Image_Gif_Scale_Denoise_waifu2x_ncnn_vulkan()
  File "Waifu2x-Extension.py", line 606, in Image_Gif_Scale_Denoise_waifu2x_ncnn_vulkan
    Process_ImageModeAB(inputPathList_folders,orginalFileNameAndFullname,JpgQuality,models,noiseLevel,scale,load_proc_save_str,tileSize,gpuId_str,saveAsJPG,delorginal)
  File "Waifu2x-Extension.py", line 795, in Process_ImageModeAB
    originalName=list(orginalFileNameAndFullname.keys())[list(orginalFileNameAndFullname.values()).index(fileName)]
ValueError: 'temp.jpg' is not in list

---------------------------------------------------
An error occurred, pls report this to the developer.

Report link:
https://github.com/AaronFeng753/Waifu2x-Extension/issues

You can download the Latest release here, maybe the bug is already fixed:
https://github.com/AaronFeng753/Waifu2x-Extension/releases/latest
-------------------------------------------
Press [Enter] key to restart the software.
```

**Comment by vbh689** [comment]
Version: `v4.0`

**Comment by AaronFeng753** [comment]
Could you tell me the full path of the folder that caused the error, and the names of all the files under that path.
Example :
`D:\folder123\123\`
`123.jpg`
`321.jpg`

**Comment by vbh689** [comment]
Update: I noticed an Unicode symbol in the image's name. After delete that character, it's work smoothly.

```
 Note: The input path must not contain special characters, which will cause compatibility problems.
┌────────────────────────────────────────────────────────────────────────────────┐
│               Scale & Denoise Image & GIF - Waifu2x-ncnn-vulkan                │
├────────────────────────────────────────────────────────────────────────────────┤
│ Type 'r' to return to the previous menu.                                       │
│                                                                                │
│ Type 'o' to stop input more path, and input path must be a folder or a file.   │
│                                                                                │
│ Scaled images & gifs will be in the input path.                                │
└────────────────────────────────────────────────────────────────────────────────┘
 Input path: C:\waifu2x\Waifu2x-Extension-v4.0-FULL-Windows-x64\1

 Input path: o

 Scan subfolders? ( y/n, default= n ): n
 Scale ratio(1/2/4/8/help, default=4): 2
 Denoise level(-1/0/1/2/3/help, default=2): 2
 Delete original files?(y/n, default=n): n
 Turn off computer when finished?(y/n, default=n): n
 Enable sleep mode?( y / n / help , default = n ):n

┌───────────────────────────────────────────────────────────────────────────────────────┐
│ Do not make any changes to the files in the input path while the software is running. │
├───────────────────────────────────────────────────────────────────────────────────────┤
│                          Press [Enter] to start processing.                           │
└───────────────────────────────────────────────────────────────────────────────────────┘


--------------------------------------------------
waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan.exe -i "C:\waifu2x\Waifu2x-Extension-v4.0-FULL-Windows-x64\1" -o "C:\waifu2x\Waifu2x-Extension-v4.0-FULL-Windows-x64\1\scaled_waifu2x" -n 2 -s 2 -t 150 -m waifu2x-ncnn-vulkan\models-upconv_7_anime_style_art_rgb -g 0 -j 2:2:2
[0 Intel(R) UHD Graphics 620]  queueC=0[1]  queueT=0[1]  memU=0  memDL=0  memHV=0
[0 Intel(R) UHD Graphics 620]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=0


Prograss(6/6): ▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮ 100%  [Time Cost: 55s ]
 Convert image.....


Copy files...
7 File(s) copied

 Total time cost:  1m : 23s


Press [Enter] key to return to the menu
```
